import os
from pathlib import Path
import shutil
from unittest.mock import MagicMock, patch

import numpy as np
from pynwb import NWBHDF5IO

from trodes_to_nwb.convert import (
    check_file_timing,
    create_nwbs,
    get_included_device_metadata_paths,
    setup_logger,
)
from trodes_to_nwb.data_scanner import get_file_info
from trodes_to_nwb.tests.utils import data_path

MICROVOLTS_PER_VOLT = 1e6


def test_get_file_info():
    path_df = get_file_info(data_path)
    path_df = path_df[
        path_df.animal == "sample"
    ]  # restrict to exclude truncated rec files

    for file_type in [
        ".h264",
        ".stateScriptLog",
        ".cameraHWSync",
        ".videoTimeStamps",
        ".videoPositionTracking",
        ".rec",
        ".trackgeometry",
        ".stateScriptLog",
    ]:
        assert len(path_df[path_df.file_extension == file_type]) == 2

    assert set(path_df.animal) == {"sample"}
    assert set(path_df.date) == {20230622}
    assert set(path_df.epoch) == {1, 2}
    assert (set(path_df.tag) == {"a1"}) or (
        set(path_df.tag) == {"a1", "NA"}
    )  # yamlfiles only added in local testing
    for file in path_df.full_path:
        assert Path(file).exists()


def test_get_included_device_metadata_paths():
    probes = list(get_included_device_metadata_paths())
    assert len(probes) == 19
    assert all(probe.exists() for probe in probes)


def test_convert_full():
    device_metadata = get_included_device_metadata_paths()

    video_directory = data_path / "temp_video_directory_full_convert"
    if not os.path.exists(video_directory):
        os.makedirs(video_directory)

    exclude_reconfig_yaml = str(data_path / "20230622_sample_metadataProbeReconfig.yml")
    create_nwbs(
        path=data_path,
        device_metadata_paths=device_metadata,
        output_dir=str(data_path),
        n_workers=1,
        query_expression=f"animal == 'sample' and full_path != '{exclude_reconfig_yaml}'",
        fs_gui_dir=data_path,
    )

    output_file_path = data_path / "sample20230622.nwb"
    assert output_file_path.exists()

    rec_to_nwb_file = data_path / "minirec20230622_.nwb"
    with NWBHDF5IO(output_file_path) as io:
        nwbfile = io.read()
        with NWBHDF5IO(rec_to_nwb_file) as io2:
            old_nwbfile = io2.read()
            # run nwb comparison
            compare_nwbfiles(nwbfile, old_nwbfile)

    output_report_path = data_path / "sample20230622_nwbinspector_report.txt"
    assert os.path.isfile(output_report_path)

    # cleanup
    os.remove(output_file_path)
    os.remove(output_report_path)
    shutil.rmtree(video_directory)


def test_convert_full_partial_iterators():
    with patch("trodes_to_nwb.convert_ephys.MAXIMUM_ITERATOR_SIZE", new=5000):
        test_convert_full()


def test_convert_full_with_inspector_error(mocker):
    def do_nothing(nwbfile, metadata_dict):
        pass

    mocker.patch("trodes_to_nwb.convert.add_subject", do_nothing)

    device_metadata = get_included_device_metadata_paths()

    video_directory = data_path / "temp_video_directory_full_convert"
    if not os.path.exists(video_directory):
        os.makedirs(video_directory)

    exclude_reconfig_yaml = str(data_path / "20230622_sample_metadataProbeReconfig.yml")
    create_nwbs(
        path=data_path,
        device_metadata_paths=device_metadata,
        output_dir=str(data_path),
        fs_gui_dir=data_path,
        n_workers=1,
        query_expression=f"animal == 'sample' and full_path != '{exclude_reconfig_yaml}'",
    )

    output_file_path = data_path / "sample20230622.nwb"

    output_report_path = data_path / "sample20230622_nwbinspector_report.txt"
    assert os.path.isfile(output_report_path)

    with open(output_report_path) as f:
        assert "Importance.CRITICAL: check_subject_exists" in f.read()

    # TODO check that the error is printed to stdout
    # 0.0  Importance.CRITICAL: check_subject_exists - 'NWBFile' object at location '/'
    #    Message: Subject is missing.

    # cleanup
    os.remove(output_file_path)
    os.remove(output_report_path)
    shutil.rmtree(video_directory)


def check_module_entries(test, reference):
    todo = [
        "camera_sample_frame_counts",
        # "video_files",
        "analog",  # moved from processing to per-sensor acquisition TimeSeries
    ]  # TODO: known missing entries
    for entry in reference:
        if entry in todo:
            continue
        assert entry in test


def compare_nwbfiles(nwbfile, old_nwbfile, truncated_size=False):
    """Compare two nwbfiles, checking that all the same entries are present and that the data matches

    Parameters
    ----------
    nwbfile : pynwb.NWBFile
        The nwbfile to be tested
    old_nwbfile : pynwb.NWBFile
        The reference nwbfile (generated by rec_to_nwb)
    truncated_size : bool, optional
        Whether the new nwbfile only contains a subset of the data, by default False
    """

    # check existence of contents
    check_module_entries(nwbfile.processing, old_nwbfile.processing)
    check_module_entries(nwbfile.acquisition, old_nwbfile.acquisition)
    check_module_entries(nwbfile.devices, old_nwbfile.devices)
    assert nwbfile.subject
    assert nwbfile.session_description
    assert nwbfile.session_id
    assert nwbfile.session_start_time
    assert nwbfile.electrodes
    assert nwbfile.experiment_description
    assert nwbfile.experimenter
    assert nwbfile.file_create_date
    assert nwbfile.identifier
    assert nwbfile.institution
    assert nwbfile.lab

    # check ephys data values
    conversion = nwbfile.acquisition["e-series"].conversion * MICROVOLTS_PER_VOLT
    assert (
        (nwbfile.acquisition["e-series"].data[0, :] * conversion).astype("int16")
        == old_nwbfile.acquisition["e-series"].data[0, :]
    ).all()
    # check data shapes match if untruncated
    assert (
        nwbfile.acquisition["e-series"].data.shape
        == old_nwbfile.acquisition["e-series"].data.shape
    ) or truncated_size
    ephys_size = nwbfile.acquisition["e-series"].data.shape[0]
    # check all values of one of the streams
    old_data = old_nwbfile.acquisition["e-series"].data[:, 0]
    ind = np.where(np.abs(old_data[:ephys_size]) > 0)[
        0
    ]  # Ignore the artifact zero valued points from rec_to_nwb_conversion
    assert (
        (nwbfile.acquisition["e-series"].data[ind, 0] * conversion).astype("int16")
        == old_data[ind]
    ).all()
    # check that timestamps are less than one sample different
    assert np.allclose(
        nwbfile.acquisition["e-series"].timestamps[:],
        old_nwbfile.acquisition["e-series"].timestamps[:ephys_size],
        rtol=0,
        atol=1.0 / 30000,
    )

    # check analog data. Analog now lives as per-sensor TimeSeries in
    # acquisition; the rec_to_nwb reference still stores a single combined
    # processing["analog"] stream. ECU analog inputs stay at the full acquisition
    # rate and must match the reference channel-for-channel. Headstage IMU sensors
    # are decimated to their true ~100 Hz rate, so they are checked separately
    # (presence + units), not against the 30 kHz held reference.
    old_analog = old_nwbfile.processing["analog"]["analog"]["analog"]
    if (
        old_analog.data.size > 0
    ):  # analog data not included in all old files. Shouldn't fail because we include it now
        imu_names = {"accelerometer", "gyroscope", "magnetometer"}
        # full-rate ECU streams: recombine raw int16 columns by channel name.
        # Skip the ephys series and the decimated IMU (different timebases); analog
        # streams encode their channel list in the description as "<desc>: a, b, c".
        new_by_channel = {}
        for name, ts in nwbfile.acquisition.items():
            if name == "e-series" or name in imu_names or ": " not in ts.description:
                continue
            channel_names = ts.description.split(": ", 1)[1].split(", ")
            for col, channel in enumerate(channel_names):
                new_by_channel[channel] = ts.data[:, col]

        old_full_order = old_analog.description.split("   ")[:-1]
        ecu_channels = [
            ch for ch in old_full_order if ch != "timestamps" and ch in new_by_channel
        ]
        assert ecu_channels  # at least the ECU analog inputs are present
        analog_size = len(new_by_channel[ecu_channels[0]])
        assert (analog_size == old_analog.data.shape[0]) or truncated_size
        # raw int16 values match the reference, per ECU channel, across all timepoints
        for old_col, channel in enumerate(old_full_order):
            if channel in new_by_channel:
                assert (
                    new_by_channel[channel][:analog_size]
                    == old_analog.data[:analog_size, old_col]
                ).all()

        # headstage IMU sensors decimated to their true rate carry physical units
        if "accelerometer" in nwbfile.acquisition:
            accel = nwbfile.acquisition["accelerometer"]
            assert accel.unit == "g" and accel.conversion == 0.000061
            assert accel.data.shape[0] < analog_size  # decimated, not held full-rate
        if "gyroscope" in nwbfile.acquisition:
            gyro = nwbfile.acquisition["gyroscope"]
            assert gyro.unit == "d/s" and gyro.conversion == 0.061

    # compare dio data
    for dio_name in old_nwbfile.processing["behavior"]["behavioral_events"].time_series:
        old_dio = old_nwbfile.processing["behavior"]["behavioral_events"][dio_name]
        current_dio = nwbfile.processing["behavior"]["behavioral_events"][dio_name]
        # check that timeseries match
        dio_size = current_dio.data.shape[0]
        np.testing.assert_array_equal(current_dio.data[:], old_dio.data[:dio_size])
        assert np.allclose(
            current_dio.timestamps[:],
            old_dio.timestamps[:dio_size],
            rtol=0,
            atol=1.0 / 30000,
        )
        assert (current_dio.unit == old_dio.unit) or (
            (current_dio.unit == "-1") and (old_dio.unit == "'unspecified'")
        )  # old rec_to_nwb conversions have a different default for unspecified units
        assert current_dio.description == old_dio.description

    # Compare position data
    for series in nwbfile.processing["behavior"]["position"].spatial_series:
        # check series in new nwbfile
        assert series in nwbfile.processing["behavior"]["position"].spatial_series
        # find the corresponding data in the old file
        validated = False
        for old_series in old_nwbfile.processing["behavior"]["position"].spatial_series:
            # check that led number matches
            if series.split("_")[1] != old_series.split("_")[1]:
                continue
            # check if timestamps end the same
            timestamps = nwbfile.processing["behavior"]["position"][series].timestamps[
                :
            ]
            old_timestamps = old_nwbfile.processing["behavior"]["position"][
                old_series
            ].timestamps[:]
            if np.allclose(
                timestamps[-30:],
                old_timestamps[-30:],
                rtol=0,
                atol=np.mean(np.diff(old_timestamps[-30:])),
            ):
                pos = nwbfile.processing["behavior"]["position"][series].data[:]
                old_pos = old_nwbfile.processing["behavior"]["position"][
                    old_series
                ].data[:]
                # check that the data is the same
                assert np.allclose(pos[-30:], old_pos[-30:], rtol=0, atol=1e-6)
                validated = True
                break
        assert validated, f"Could not find matching series for {series}"


def _make_mock_io(start_ns, end_ns, filename="file.rec", sys_clock=True):
    """Helper to create a mock SpikeGadgetsRawIO-like object."""
    mock_io = MagicMock()
    mock_io.get_sys_clock.side_effect = lambda start, end: (
        [start_ns] if end == 1 else [end_ns]
    )
    mock_io._raw_memmap.shape = (100, 1)
    mock_io._raw_memmap.filename = filename
    mock_io.sysClock_byte = sys_clock
    mock_io.system_time_at_creation = start_ns / 1e6  # in milliseconds
    return mock_io


def test_check_file_timing_valid_single_file():
    """check_file_timing should not raise for a single valid file."""
    start_ns = int(1e18)  # ~31 years in nanoseconds, valid Unix time in seconds
    end_ns = start_ns + int(60 * 1e9)  # 60 seconds later
    mock_io = _make_mock_io(start_ns, end_ns)

    with patch("trodes_to_nwb.convert.SpikeGadgetsRawIO") as MockRawIO:
        MockRawIO.return_value = mock_io
        # Should not raise
        check_file_timing(["file.rec"], setup_logger("test", "test.log"))


def test_check_file_timing_valid_multiple_files():
    """check_file_timing should not raise for multiple ordered valid files."""
    base_ns = int(1e18)
    mock_io1 = _make_mock_io(base_ns, base_ns + int(60 * 1e9), "file1.rec")
    mock_io2 = _make_mock_io(
        base_ns + int(120 * 1e9), base_ns + int(180 * 1e9), "file2.rec"
    )

    with patch("trodes_to_nwb.convert.SpikeGadgetsRawIO") as MockRawIO:
        MockRawIO.side_effect = [mock_io1, mock_io2]
        # Should not raise
        check_file_timing(["file1.rec", "file2.rec"], setup_logger("test", "test.log"))


def test_check_file_timing_valid_multiple_files_no_sys_clock():
    """check_file_timing should not raise for multiple ordered valid files."""
    base_ns = int(1e18)
    mock_io1 = _make_mock_io(
        base_ns, base_ns + int(60 * 1e9), "file1.rec", sys_clock=False
    )
    mock_io2 = _make_mock_io(
        base_ns + int(120 * 1e9), base_ns + int(180 * 1e9), "file2.rec", sys_clock=False
    )

    with patch("trodes_to_nwb.convert.SpikeGadgetsRawIO") as MockRawIO:
        MockRawIO.side_effect = [mock_io1, mock_io2]
        # Should not raise
        check_file_timing(["file1.rec", "file2.rec"], setup_logger("test", "test.log"))


def test_check_file_timing_negative_duration_raises():
    """check_file_timing should raise ValueError when end time is before start time."""
    start_ns = int(1e18)
    end_ns = start_ns - int(10 * 1e9)  # end before start
    mock_io = _make_mock_io(start_ns, end_ns)

    with patch("trodes_to_nwb.convert.SpikeGadgetsRawIO") as MockRawIO:
        MockRawIO.return_value = mock_io
        try:
            check_file_timing(["file.rec"], logger=setup_logger("test", "test.log"))
            assert False, "Expected ValueError for negative duration"
        except ValueError:
            pass


def test_check_file_timing_out_of_order_raises():
    """check_file_timing should raise ValueError when files are out of order."""
    base_ns = int(1e18)
    # file2 starts before file1 ends and before file1 starts
    mock_io1 = _make_mock_io(
        base_ns + int(120 * 1e9), base_ns + int(180 * 1e9), "file1.rec"
    )
    mock_io2 = _make_mock_io(base_ns, base_ns + int(60 * 1e9), "file2.rec")

    with patch("trodes_to_nwb.convert.SpikeGadgetsRawIO") as MockRawIO:
        MockRawIO.side_effect = [mock_io1, mock_io2]
        try:
            check_file_timing(
                ["file1.rec", "file2.rec"], logger=setup_logger("test", "test.log")
            )
            assert False, "Expected ValueError for out of order files"
        except ValueError:
            pass


def test_check_file_timing_equal_start_times_raises():
    """check_file_timing should raise ValueError when two files have the same start time."""
    base_ns = int(1e18)
    mock_io1 = _make_mock_io(base_ns, base_ns + int(60 * 1e9), "file1.rec")
    mock_io2 = _make_mock_io(base_ns, base_ns + int(120 * 1e9), "file2.rec")

    with patch("trodes_to_nwb.convert.SpikeGadgetsRawIO") as MockRawIO:
        MockRawIO.side_effect = [mock_io1, mock_io2]
        try:
            check_file_timing(
                ["file1.rec", "file2.rec"], logger=setup_logger("test", "test.log")
            )
            assert False, "Expected ValueError for equal start times"
        except ValueError:
            pass


def test_check_file_timing_empty_list():
    """check_file_timing should not raise for an empty list."""
    check_file_timing([], logger=setup_logger("test", "test.log"))


def test_check_file_timing_parses_header():
    """check_file_timing should call parse_header for each file."""
    base_ns = int(1e18)
    mock_io = _make_mock_io(base_ns, base_ns + int(60 * 1e9))

    with patch("trodes_to_nwb.convert.SpikeGadgetsRawIO") as MockRawIO:
        MockRawIO.return_value = mock_io
        check_file_timing(["file.rec"], logger=setup_logger("test", "test.log"))
        mock_io.parse_header.assert_called_once()
